name: Continuous Integration

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Test with pytest
        run: |
          poetry run python -m unittest discover -p "test_*.py"
  quality:
    name: Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Lint with pylint
        run: |
          poetry run pylint **/*.py
      - name: Check types with mypy
        run: |
          poetry run mypy **/*.py
      - name: Coverage with coverage
        run: |
          poetry run coverage run -m unittest discover -p "test_*.py"
          poetry run coverage report -m