name: Security

on:
  workflow_run:
    workflows:
      - 'Continuous Integration'
    types:
      - completed

jobs:
  find-secrets:
    name: 'Find Secrets'
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]') && (${{ github.event.workflow_run.conclusion == 'success' }})
    steps:
      - uses: actions/checkout@v2
      - name: Find Secrets
        uses: max/secret-scan@master
        with:
          exclude_path: '.github/workflows/configuration/exclude_paths.txt'
  sast:
    name: 'SAST'
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]') && (${{ github.event.workflow_run.conclusion == 'success' }})
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run Bandit
        run: |
          poetry run bandit -r .
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/ci
            p/security-audit
            p/secrets
  sca:
    name: 'SCA'
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]') && (${{ github.event.workflow_run.conclusion == 'success' }})
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run Saftey
        run: |
          poetry run safety check